### ISSUE TITLE
Unexpected end of JSON input

### ISSUE THREAD

**Issue by remorses** [h2non/youtube-video-api#30]
i am running command on the video folder:
`youtube-video-api upload -c “xxxxxxxxx5n027c.apps.googleusercontent.com” -s “xxxxxxxxxxVLFAZ” -f “config.json” -v video.mp4`

with config.json file:
```
{
  "resource": {
    "snippet": {
      "title": "test video",
      "description": "This is a test video uploaded via the YouTube API"
    },
    "status": {
      "privacyStatus": "private"
    }
  }
}
```
But I get error:
`Command failed: Unexpected end of JSON input
`

**Comment by remorses** [comment]
With debug -d enabled:
```
Command failed: Unexpected end of JSON input
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at YoutubeVideo.oauthLazyHandshake (/usr/local/lib/node_modules/youtube-video-api/index.js:114:19)
    at YoutubeVideo.auth.YoutubeVideo.authenticate (/usr/local/lib/node_modules/youtube-video-api/index.js:106:22)
    at /usr/local/lib/node_modules/youtube-video-api/bin/youtube-video-api:137:10
    at run (/usr/local/lib/node_modules/youtube-video-api/bin/youtube-video-api:203:5)
    at Object.<anonymous> (/usr/local/lib/node_modules/youtube-video-api/bin/youtube-video-api:136:1)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
```
