### ISSUE TITLE
error message like a timeout

### ISSUE THREAD

**Issue by mo3een-ameen** [h2non/youtube-video-api#32]
I am getting the below error.  Do you know what it could be please? My tokens are working in another context.  This feels like a timeout, but using another API to query the youtube API it works fine.
Whether I try to upload a video or run the below command, I am getting the same error.

Thank you in advance for your help.

This is the command
node youtube-video-api list -c clientId -s clientSecret --next

This is the error:

\youtube-video-api\bin\youtube-video-api:222
  console.error('Command failed:', err.message || err)
                                       ^

TypeError: Cannot read property 'message' of undefined
    at error (\youtube-video-api\bin\youtube-video-api:222:40)
    at \youtube-video-api\bin\youtube-video-api:138:21
    at \youtube-video-api\index.js:146:14
    at \youtube-video-api\node_modules\nightmare-google-oauth2\index.js:114:21
    at \youtube-video-api\node_modules\nightmare-google-oauth2\index.js:239:10
    at Timeout._onTimeout (\youtube-video-api\node_modules\nightmare-google-oauth2\index.js:179:9)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)

**Comment by mo3een-ameen** [comment]
It was just missing the config file, not in the correct folder
